### ISSUE TITLE
Accordion component issue

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/inspiredfencing#3]
Hi @jimafisk 

Just wanted to add this issue as discussed.

The FAQ accordion component linked [here](https://github.com/jamestagal/inspiredfencing/blob/main/layouts/components/faq_1346.svelte) only works when reloading the page which tiggers the html fallback that gets a trailing backslash. 

So when the route is like this - http://localhost:3000/inspiredfencing/areas/ the ```active``` class works. ( I have added the active class to each  ```li``` so that the accordion is open ```active``` so the visitor doesn't have to click to open each panel. 

I think you suggested that there might be a better approach here... such as pulling out each ```li``` into an array? and make it editable via the CMS. 
Any suggestion here would be much appreciated. 

best regards,

Ben

**Comment by jimafisk** [comment]
Hey @jamestagal,

This issue that was happening here is you were loading the `faq.js` script in your `<head>` statically, which would load on an initial page refresh and immediately run a [document.querySelectorAll()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) to get the FAQ items. This would work if you reloaded the "areas" page because there were FAQ items, but if you refreshed on a different page (like the homepage) there were no FAQ items to load and if you later navigated to the "areas" page, that script already had run and there were no items loaded - it would not know to run again. 

I ended up just removing the FAQ script entirely and put some basic svelte to swap classes directly inside the component instead. 

**Important:** I only did this for the first 2 FAQ items to demonstrate how to do it. You still need to copy the other HTML items into a basic list to get the others to work. You should be able to follow the format there. 

**Recommendations:**
- I recommend moving this list out of the top of the `layouts/components/faq_1346.svelte` component and putting it into the `content/pages/areas.json` content source. That would let editors have the ability to change this info in the future. 
- I know I'm the one that did this, but I would remove the `options` variable entirely and just pull the `title`s out of the `values` variable instead. That would just decrease the likelihood of these things getting out of sync. You would then set the initial value lie `let selected = values[0]?.title;`

Hope that helps!

**Comment by jamestagal** [comment]
Thanks Jim.

I will work on making these changes today and let you know how I go.

Thanks again. 😄

**Comment by jamestagal** [comment]
Hi @jimafisk 

Thank you so much for helping with this one. After making your recommended changes It all works great.

I am still trying to understand your second recommendation but I will think about it more... 😀 to get a grasp on it. 

> I know I'm the one that did this, but I would remove the `options` variable entirely and just pull the `title`s out of the `values` variable instead. That would just decrease the likelihood of these things getting out of sync. You would then set the initial value lie `let selected = values[0]?.title;`

Thanks again.

**Comment by jamestagal** [comment]
Hi @jimafisk 

I have looked at added your recommendation from your last dot point from above.

This is what it looks like in the script tag now:

```javascript
let selected = area_Options[0]?.title;
```

The only different re the UI now is that the first item in the index it not active...when you load the page.

So how could I pass the index into the initial state so that the first ```area_Option``` item is loaded on the page?

```svelte
        {#each area_Options as area_Option, i}
          <button
            class="cs-option{selected === area_Option ? ' cs-active' : ''}"
            on:click={() => (selected = area_Option)}
            data-filter={i}
          >
            {area_Option}
          </button>
        {/each}
```

**Comment by jamestagal** [comment]
Hi @jimafisk 

I figured out this one. I just had the wrong field value for the ```selected``` initial variable.  It needed to be the ```area_Lists``` not  the ```area_Options```. As below.

```javascript
let selected = area_Lists[0]?.title;
```

**Comment by jimafisk** [comment]
Awesome, glad you figured it out @jamestagal!
